apiVersion: v1
kind: Service
metadata:
  name: rust-proxy
  labels:
    app: rust-proxy
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: rust-proxy
  ports:
    - name: proxy
      port: 8080
      targetPort: proxy
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
